#http:
#  server:
#    port: 65531 #65531自动跳转8443

server:
#  port: 8443
  port: 65531
  servlet:
    context-path: /
#  ssl:
#    key-store: classpath:cert/demo.keystore
#    key-store-password: 12345678
#    key-alias: openapi-tomcat

# logback 配置
logging:
  file:
    path: classpath:/logback-spring.xml
  level:
    root: debug
    boot: info
  path: logs

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yiidii.cn:3306/openapi?useUnicode=true&characterEncoding=UTF-8
    password: Wed114130
#    password: 114130
    username: root

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: UUID


justauth:
  enabled: true
  type:
    github:
      client-id: 4417952588fc4ba8b9d6
      client-secret: 81220cef45c226c02697d07b7ebb6638c552a01e
      redirect-uri: http://127.0.0.1:65531/oauth/callback

