server:
  port: 65531
  servlet:
    context-path: /openapi/v1

# logback 配置
logging:
  file:
    path: classpath:/logback-spring.xml
  level:
    root: debug
    boot: info
  path: logs

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 114130
    url: jdbc:mysql://localhost:3306/openapi?useUnicode=true&characterEncoding=UTF-8
    username: root

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

